const actionTypes = {
    "CAN_CASTLE" : "CAN_CASTLE",
    "CLEAR_CANDIDATE_MOVES" : "CLEAR_CANDIDATE_MOVES",
    "GENERATE_CANDIDATE_MOVES" : "GENERATE_CANDIDATE_MOVES",
    "NEW_MOVE" : "NEW_MOVE",
    "NEW_GAME" : "NEW_GAME",
    "PROMOTION_CLOSE" : "PROMOTION_CLOSE",
    "PROMOTION_OPEN" : "PROMOTION_OPEN",
    "STALEMATE" : "STALEMATE",
    "INSUFFICIENT_MATERIAL" : "INSUFFICIENT_MATERIAL",
    "WIN" : "WIN",
    "TAKE_BACK" : "TAKE_BACK",
    "THEME": "THEME",
    "CLEAR_HIGHLIGHTS": "CLEAR_HIGHLIGHTS",
    "HIGHLIGHT_SQUARE": "HIGHLIGHT_SQUARE",
    "SET_CANDIDATE_SQUARE": "SET_CANDIDATE_SQUARE",
    "FLIP_BOARD": "FLIP_BOARD",
    "CHANGE_SETTINGS": "CHANGE_SETTINGS",
    "INIT_SETTINGS": "INIT_SETTINGS"
}

export default actionTypes